#!/bin/bash

if [[ -z $1 ]]; then
    echo "Usage: $0 [ID]"
    exit 1
fi

 curl -s -X POST -d "parcelnumber=6H11386796562" http://www.colissimo.fr/portail_colissimo/suivreResultatStubs.do|grep -Pzo '<td headers="Libelle">(.*?)<\/td>'

exit 0
